package view;

import controller.CriarListagemController;
import java.awt.Point;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Clinica;
import model.Medico;
import model.Servico;

/**
 *
 */
public class CriarListagemUI extends javax.swing.JDialog {

    /**
     * Janela principal da aplicação.
     */
    private java.awt.Frame framePai;

    /**
     * Controlador da funcionalidade que permite apresentar a listagem dos
     * serviços realizados e o material utilizado em cada um, por médico.
     */
    private CriarListagemController controlador;

    /**
     * Creates new form CriarListagemUI
     *
     * @param parent
     * @param modal
     * @param clinica
     */
    public CriarListagemUI(java.awt.Frame parent, boolean modal, Clinica clinica) {
        super(parent, "Criar Listagem", modal);
        this.framePai = parent;
        this.controlador = new CriarListagemController(clinica);
        initComponents();
        propriedadesJanela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelDataInicio = new javax.swing.JLabel();
        jLabelDataFim = new javax.swing.JLabel();
        jXDatePickerInicio = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerFim = new org.jdesktop.swingx.JXDatePicker();
        jComboBoxMedicos = new javax.swing.JComboBox<>();
        jLabelMedicos = new javax.swing.JLabel();
        jLabelServicos = new javax.swing.JLabel();
        jComboBoxServicos = new javax.swing.JComboBox<>();
        jLabelMaterial = new javax.swing.JLabel();
        jComboBoxMaterial = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonProcurar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDataInicio.setText("Data Inicio:");

        jLabelDataFim.setText("Data fim:");

        jComboBoxMedicos.setEnabled(false);
        jComboBoxMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMedicosActionPerformed(evt);
            }
        });

        jLabelMedicos.setText("Médicos:");

        jLabelServicos.setText("Serviços:");

        jComboBoxServicos.setEnabled(false);
        jComboBoxServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicosActionPerformed(evt);
            }
        });

        jLabelMaterial.setText("Material:");

        jComboBoxMaterial.setEnabled(false);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonProcurar.setText("Procurar");
        jButtonProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxServicos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxMedicos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelServicos)
                            .addComponent(jLabelMaterial)
                            .addComponent(jLabelMedicos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDataInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jXDatePickerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDataFim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jXDatePickerFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonProcurar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePickerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePickerFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataFim)
                    .addComponent(jLabelDataInicio)
                    .addComponent(jButtonProcurar))
                .addGap(18, 18, 18)
                .addComponent(jLabelMedicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarActionPerformed
        try {
            Date dataInicio = this.jXDatePickerInicio.getDate();
            Date dataFim = this.jXDatePickerFim.getDate();

            DefaultComboBoxModel modelo = this.controlador.getListaMedicosServicosMaterial(dataInicio, dataFim);

            if (modelo.getSize() == 0) {
                JOptionPane.showMessageDialog(
                        framePai,
                        "Não existem dados para apresentar, a janela vai ser fechada.",
                        "Listar Serviços",
                        JOptionPane.ERROR_MESSAGE);
                dispose();
            }

            this.jComboBoxMedicos.setModel(modelo);

            this.jXDatePickerInicio.setEnabled(false);
            this.jXDatePickerFim.setEnabled(false);
            this.jButtonProcurar.setEnabled(false);
            this.jComboBoxMedicos.setEnabled(true);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    "As datas não foram devidamente preenchidas",
                    "Listar Serviços",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    "Listar Serviços",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonProcurarActionPerformed

    private void jComboBoxMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMedicosActionPerformed
        Medico medico = (Medico) this.jComboBoxMedicos.getSelectedItem();

        this.jComboBoxServicos.setEnabled(true);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(medico.getListaServicos().toArray());
        this.jComboBoxServicos.setModel(modelo);
        this.jComboBoxMaterial.setEnabled(false);
        this.jComboBoxMaterial.setModel(new DefaultComboBoxModel());

    }//GEN-LAST:event_jComboBoxMedicosActionPerformed

    private void jComboBoxServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicosActionPerformed
        Servico servico = (Servico) this.jComboBoxServicos.getSelectedItem();

        this.jComboBoxMaterial.setEnabled(true);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(servico.getListaMaterial().toArray());
        this.jComboBoxMaterial.setModel(modelo);
    }//GEN-LAST:event_jComboBoxServicosActionPerformed

    private void propriedadesJanela() {
        pack();
        setLocation(new Point(this.framePai.getX() + this.framePai.getWidth(), this.framePai.getY()));
        setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonProcurar;
    private javax.swing.JComboBox<String> jComboBoxMaterial;
    private javax.swing.JComboBox<Medico> jComboBoxMedicos;
    private javax.swing.JComboBox<Servico> jComboBoxServicos;
    private javax.swing.JLabel jLabelDataFim;
    private javax.swing.JLabel jLabelDataInicio;
    private javax.swing.JLabel jLabelMaterial;
    private javax.swing.JLabel jLabelMedicos;
    private javax.swing.JLabel jLabelServicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerFim;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerInicio;
    // End of variables declaration//GEN-END:variables
}
