package view;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Clinica;

public class Janela extends javax.swing.JFrame {

    /**
     * Clinica dentária.
     */
    private Clinica clinica;

    /**
     * Creates new form Janela
     *
     * @param clinica Clinica dentária.
     */
    public Janela(Clinica clinica) {
        this.clinica = clinica;
        initComponents();
        propriedadesJanela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registarPaciente = new javax.swing.JButton();
        listarServicos = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        alterarPaciente = new javax.swing.JButton();
        registarServicos = new javax.swing.JButton();
        listarAgenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registarPaciente.setText("Registar Paciente");
        registarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarPacienteActionPerformed(evt);
            }
        });

        listarServicos.setText("Listar Serviços");
        listarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarServicosActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        alterarPaciente.setText("Alterar Dados do Paciente");
        alterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarPacienteActionPerformed(evt);
            }
        });

        registarServicos.setText("Registar Serviços na Consulta");
        registarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarServicosActionPerformed(evt);
            }
        });

        listarAgenda.setText("Listar Agenda de Consultas");
        listarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alterarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registarServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registarServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listarAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listarServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void propriedadesJanela() {
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private void registarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarPacienteActionPerformed
        new RegistarPacienteUI(this, true, this.clinica).setVisible(true);
    }//GEN-LAST:event_registarPacienteActionPerformed

    private void listarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarServicosActionPerformed
        new CriarListagemUI(this, true, this.clinica).setVisible(true);
    }//GEN-LAST:event_listarServicosActionPerformed

    private void alterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarPacienteActionPerformed
        new AlterarPacienteUI(this, true, this.clinica).setVisible(true);
    }//GEN-LAST:event_alterarPacienteActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void registarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarServicosActionPerformed
        new RegistarServicosConsulta(this, true, this.clinica).setVisible(true);
    }//GEN-LAST:event_registarServicosActionPerformed

    private void listarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarAgendaActionPerformed
        new ListarAgendaMedicoUI(this, true, this.clinica).setVisible(true);
    }//GEN-LAST:event_listarAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Janela(new Clinica()).setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(
                            null, "Não foi possível ligar à Base de Dados.",
                            "Ligação à BD", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarPaciente;
    private javax.swing.JButton listarAgenda;
    private javax.swing.JButton listarServicos;
    private javax.swing.JButton registarPaciente;
    private javax.swing.JButton registarServicos;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
