CREATE SEQUENCE seq_project MINVALUE 1 MAXVALUE 200 START WITH 1 INCREMENT BY 1;

CREATE SEQueNCE seq_junction MINVALUE 1 MAXVALUE 200 START WITH 1 INCREMENT BY 1;

CREATE SEQueNCE seq_roadtypology MINVALUE 1 MAXVALUE 200 START WITH 1 INCREMENT BY 1;

CREATE SEQueNCE seq_section MINVALUE 1 MAXVALUE 200 START WITH 1 INCREMENT BY 1;

CREATE SEQueNCE seq_segment MINVALUE 1 MAXVALUE 200 START WITH 1 INCREMENT BY 1;
